"""add refresh_token_blocklist table

Revision ID: 8caaef524476
Revises: c989bf3c290d
Create Date: 2026-06-14 00:10:46.335471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8caaef524476'
down_revision: Union[str, None] = 'c989bf3c290d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_token_blocklist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('blocked_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_token_blocklist_token_hash'), 'refresh_token_blocklist', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_token_blocklist_token_hash'), table_name='refresh_token_blocklist')
    op.drop_table('refresh_token_blocklist')
    # ### end Alembic commands ###
